#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Andrewhood125\Provisioner\Commands\ProvisionDebianCommand;
use Andrewhood125\Provisioner\Commands\InstallCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ProvisionDebianCommand());
$application->add(new InstallCommand());
$application->run();
